[behave]
# By default, we use plain output for console readability
default_format = plain
show_timings = true
show_skipped = false
logging_level = INFO
log_capture  = true

[behave.userdata]
browser  = chromium
headless = false
base_url = https://www.daraz.pk